export const sliderItems = [
  {
    id: 1,
    img: "https://th.bing.com/th/id/R.be72e8c89cae6044296301f0eaf6549a?rik=GHxSupP7d5Kjlg&riu=http%3a%2f%2fpluspng.com%2fimg-png%2fmodel-png-random-model-png-19-by-dreamervisen-738.png&ehk=Pet20POR9IpYR%2fF%2fwiFywRN3I9TrBXn90ksFyMtM4lc%3d&risl=&pid=ImgRaw&r=0",
    title: "SUMMER SALE",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: "f5fafd",
  },
  {
    id: 2,
    img: "https://i.ibb.co/DG69bQ4/2.png",
    title: "AUTUMN COLLECTION",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS. ",
    bg: "fcf1ed",
  },
  {
    id: 3,
    img: "https://orig00.deviantart.net/ee86/f/2016/080/1/f/9a1c23bbc397d809a558eff821b427dc_by_msoranzhevaya-d9vw66l.png",
    title: "LONGEWEAR LOVE",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: "fbf0f4",
  },
];

export const categories = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/5886041/pexels-photo-5886041.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    title: "SHIRT STYLE!",
    cat: "shirt",
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    title: "LOUNGEWEAR LOVE",
    cat: "longewear",
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/5480696/pexels-photo-5480696.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    title: "LIGHT JACKETS",
    cat: "jacket",
  },
];

export const footerList = [
  {
    text: "Home",
  },
  {
    text: "Cart",
  },
  {
    text: "Man Fashion",
  },
  {
    text: "Woman Fashion",
  },
  {
    text: "Accessories",
  },
  {
    text: "My Account",
  },
  {
    text: "Order Tracking",
  },

  {
    text: "Wishlist",
  },
  {
    text: "Temrs",
  },
];

export const filterProducts = {
  color: ["white", "red", "blue", "yellow", "green"],
  size: ["XS", "S", "M", "L", "XL"],
};

export const sortProducts = [
  {
    id: 1,
    text: "Newest",
    value: "newest",
  },
  {
    id: 2,
    text: "Price asc",
    value: "asc",
  },
  {
    id: 3,
    text: "Price desc",
    value: "desc",
  },
];

export const popularProducts = [
  {
    id: 11,
    img: "https://pngimg.com/uploads/polo_shirt/polo_shirt_PNG8155.png",
    size: ["M", "L"],
    color: ["whitesmoke"],
    cat: ["shirt"],
    title: "Laptop",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod lacinia at quis risus sed vulputate odio. In pellentesque massa placerat duis ultricies. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam.",
    price: 300,
    quantity: 5,
    release: "03/25/2020",
  },
  {
    id: 9,
    img: "https://th.bing.com/th/id/R.d1859b4fa598cd6480cbdb48283724fa?rik=WgkBVDGIhKERtg&riu=http%3a%2f%2fth04.deviantart.net%2ffs70%2fPRE%2fi%2f2013%2f223%2f5%2f6%2fbarbara_palvin_png_by_vs_angel-d6hnxxg.png&ehk=0jGFkBLy7Y0UjNlfkPRKTP5ShgY6xm1ZtXjTLFyyalo%3d&risl=&pid=ImgRaw&r=0",
    size: ["M", "L"],
    color: ["orange"],
    cat: ["longewear"],
    title: "Laptop",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod lacinia at quis risus sed vulputate odio. In pellentesque massa placerat duis ultricies. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam.",
    price: 300,
    quantity: 5,
    release: "03/25/2020",
  },
  {
    id: 2,
    img: "https://purepng.com/public/uploads/large/purepng.com-helly-hansen-daybreaker-fleece-jacket-womengarmentupper-bodyjacketlighterladieshelly-hansendaybreakerfleece-142152636173585qyc.png",
    size: ["L", "S"],
    color: ["pink"],
    cat: ["jacket"],
    title: "Laptop",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod lacinia at quis risus sed vulputate odio. In pellentesque massa placerat duis ultricies. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam.",
    price: 200,
    quantity: 5,
    release: "03/25/2021",
  },
];

export const products = [
  {
    id: 1,
    img: "https://www.freepnglogos.com/uploads/jacket-png/leather-women-jacket-transparent-png-stickpng-28.png",
    size: ["XL", "M", "L"],
    color: ["brown"],
    cat: ["jacket"],
    title: "Brown Jacket",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod lacinia at quis risus sed vulputate odio. In pellentesque massa placerat duis ultricies. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam.Convallis aenean et tortor at risus viverra. Integer feugiat scelerisque varius morbi enim nunc faucibus a. Morbi non arcu risus quis varius quam quisque. Ut eu sem integer vitae justo eget magna fermentum. Ante in nibh mauris cursus mattis molestie a iaculis at.",
    price: 70,
    quantity: 5,
    release: "03/25/2000",
  },
  {
    id: 2,
    img: "https://purepng.com/public/uploads/large/purepng.com-helly-hansen-daybreaker-fleece-jacket-womengarmentupper-bodyjacketlighterladieshelly-hansendaybreakerfleece-142152636173585qyc.png",
    size: ["L", "S"],
    color: ["pink"],
    cat: ["jacket"],
    title: "Classic Jacket",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod lacinia at quis risus sed vulputate odio. In pellentesque massa placerat duis ultricies. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam.Convallis aenean et tortor at risus viverra. Integer feugiat scelerisque varius morbi enim nunc faucibus a. Morbi non arcu risus quis varius quam quisque. Ut eu sem integer vitae justo eget magna fermentum. Ante in nibh mauris cursus mattis molestie a iaculis at.",
    price: 65,
    quantity: 5,
    release: "03/25/2021",
  },
  {
    id: 3,
    img: "https://freepngimg.com/thumb/blazer/3-2-blazer-free-download-png.png",
    size: ["M", "L"],
    color: ["pink"],
    cat: ["jacket"],
    title: "Pink Jacket",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod lacinia at quis risus sed vulputate odio. In pellentesque massa placerat duis ultricies. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam.Convallis aenean et tortor at risus viverra. Integer feugiat scelerisque varius morbi enim nunc faucibus a. Morbi non arcu risus quis varius quam quisque. Ut eu sem integer vitae justo eget magna fermentum. Ante in nibh mauris cursus mattis molestie a iaculis at.",
    price: 80,
    quantity: 5,
    release: "03/25/2020",
  },
  {
    id: 4,
    img: "https://th.bing.com/th/id/R.4d9acde541d9175df9d6958b10475287?rik=zzC%2f9msvxoRANw&pid=ImgRaw&r=0",
    size: ["M", "L"],
    color: ["gray"],
    cat: ["jacket"],
    title: "Gray Jacket",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod lacinia at quis risus sed vulputate odio. In pellentesque massa placerat duis ultricies. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam.Convallis aenean et tortor at risus viverra. Integer feugiat scelerisque varius morbi enim nunc faucibus a. Morbi non arcu risus quis varius quam quisque. Ut eu sem integer vitae justo eget magna fermentum. Ante in nibh mauris cursus mattis molestie a iaculis at.",
    price: 55,
    quantity: 5,
    release: "03/25/2020",
  },
  {
    id: 5,
    img: "https://th.bing.com/th/id/R.4aa43def0bb4399044cd83d4a5fc6342?rik=InezImQtRxf0Xg&pid=ImgRaw&r=0",
    size: ["M", "L"],
    color: ["black"],
    cat: ["jacket"],
    title: "Black Jacket",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod lacinia at quis risus sed vulputate odio. In pellentesque massa placerat duis ultricies. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam.Convallis aenean et tortor at risus viverra. Integer feugiat scelerisque varius morbi enim nunc faucibus a. Morbi non arcu risus quis varius quam quisque. Ut eu sem integer vitae justo eget magna fermentum. Ante in nibh mauris cursus mattis molestie a iaculis at.",
    price: 95,
    quantity: 5,
    release: "03/25/2020",
  },
  {
    id: 6,
    img: "https://th.bing.com/th/id/R.dfb7953720c081e785654aaf83daa0d3?rik=6Cr0X%2bFR0kdCRg&riu=http%3a%2f%2ffc07.deviantart.net%2ffs71%2ff%2f2013%2f189%2f0%2f7%2fmiranda_kerr_png_by_vs_angel-d6cihcl.png&ehk=JOHVDGsW4y%2b3hBxAk4C77Xqtbqj1oye2iYj0cMaW54M%3d&risl=&pid=ImgRaw&r=0",
    size: ["M", "L"],
    color: ["green"],
    cat: ["longewear"],
    title: "Green Longewear",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod lacinia at quis risus sed vulputate odio. In pellentesque massa placerat duis ultricies. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam.Convallis aenean et tortor at risus viverra. Integer feugiat scelerisque varius morbi enim nunc faucibus a. Morbi non arcu risus quis varius quam quisque. Ut eu sem integer vitae justo eget magna fermentum. Ante in nibh mauris cursus mattis molestie a iaculis at.",
    price: 25,
    quantity: 5,
    release: "03/25/2020",
  },
  {
    id: 7,
    img: "https://www.freepngimg.com/thumb/model/5-2-model-png.png",
    size: ["M", "L"],
    color: ["whitesmoke"],
    cat: ["longewear"],
    title: "White Longewear",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod lacinia at quis risus sed vulputate odio. In pellentesque massa placerat duis ultricies. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam.Convallis aenean et tortor at risus viverra. Integer feugiat scelerisque varius morbi enim nunc faucibus a. Morbi non arcu risus quis varius quam quisque. Ut eu sem integer vitae justo eget magna fermentum. Ante in nibh mauris cursus mattis molestie a iaculis at.",
    price: 30,
    quantity: 5,
    release: "03/25/2020",
  },
  {
    id: 8,
    img: "https://th.bing.com/th/id/R.e6f5aaf33cd87c34f6a51a1d0e979c85?rik=MldIdFyke%2btbyQ&riu=http%3a%2f%2fpngimg.com%2fuploads%2fdress%2fdress_PNG109.png&ehk=YSukSYDyxHb5H%2buaDV%2fd1WgP3RIOfHCM6VCWAUeGWHI%3d&risl=&pid=ImgRaw&r=0",
    size: ["M", "L"],
    color: ["black"],
    cat: ["longewear"],
    title: "Suitable Longewear",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod lacinia at quis risus sed vulputate odio. In pellentesque massa placerat duis ultricies. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam.Convallis aenean et tortor at risus viverra. Integer feugiat scelerisque varius morbi enim nunc faucibus a. Morbi non arcu risus quis varius quam quisque. Ut eu sem integer vitae justo eget magna fermentum. Ante in nibh mauris cursus mattis molestie a iaculis at.",
    price: 12,
    quantity: 5,
    release: "03/25/2020",
  },
  {
    id: 9,
    img: "https://th.bing.com/th/id/R.d1859b4fa598cd6480cbdb48283724fa?rik=WgkBVDGIhKERtg&riu=http%3a%2f%2fth04.deviantart.net%2ffs70%2fPRE%2fi%2f2013%2f223%2f5%2f6%2fbarbara_palvin_png_by_vs_angel-d6hnxxg.png&ehk=0jGFkBLy7Y0UjNlfkPRKTP5ShgY6xm1ZtXjTLFyyalo%3d&risl=&pid=ImgRaw&r=0",
    size: ["M", "L"],
    color: ["orange"],
    cat: ["longewear"],
    title: "Orange Longewear",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod lacinia at quis risus sed vulputate odio. In pellentesque massa placerat duis ultricies. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam.Convallis aenean et tortor at risus viverra. Integer feugiat scelerisque varius morbi enim nunc faucibus a. Morbi non arcu risus quis varius quam quisque. Ut eu sem integer vitae justo eget magna fermentum. Ante in nibh mauris cursus mattis molestie a iaculis at.",
    price: 17,
    quantity: 5,
    release: "03/25/2020",
  },
  {
    id: 10,
    img: "https://th.bing.com/th/id/R.13a61b1cde81f2d8bd5023f67a2c320d?rik=%2bsa7otlHSFs0OQ&riu=http%3a%2f%2fpngimg.com%2fuploads%2fdancer%2fdancer_PNG117.png&ehk=6whV8OTvJvt8a%2f5oBXpI4GMmv5EiduqevX8TcyXR3Sk%3d&risl=&pid=ImgRaw&r=0",
    size: ["M", "L"],
    color: ["black"],
    cat: ["longewear"],
    title: "Black Longewear",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod lacinia at quis risus sed vulputate odio. In pellentesque massa placerat duis ultricies. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam.Convallis aenean et tortor at risus viverra. Integer feugiat scelerisque varius morbi enim nunc faucibus a. Morbi non arcu risus quis varius quam quisque. Ut eu sem integer vitae justo eget magna fermentum. Ante in nibh mauris cursus mattis molestie a iaculis at.",
    price: 20,
    quantity: 5,
    release: "03/25/2020",
  },
  {
    id: 11,
    img: "https://pngimg.com/uploads/polo_shirt/polo_shirt_PNG8155.png",
    size: ["M", "L"],
    color: ["whitesmoke"],
    cat: ["shirt"],
    title: "Fashion Shirt",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod lacinia at quis risus sed vulputate odio. In pellentesque massa placerat duis ultricies. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam.Convallis aenean et tortor at risus viverra. Integer feugiat scelerisque varius morbi enim nunc faucibus a. Morbi non arcu risus quis varius quam quisque. Ut eu sem integer vitae justo eget magna fermentum. Ante in nibh mauris cursus mattis molestie a iaculis at.",
    price: 22,
    quantity: 5,
    release: "03/25/2020",
  },
  {
    id: 12,
    img: "https://pngimg.com/uploads/tshirt/tshirt_PNG5453.png",
    size: ["M", "L"],
    color: ["pink"],
    cat: ["shirt"],
    title: "Pink Shirt",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod lacinia at quis risus sed vulputate odio. In pellentesque massa placerat duis ultricies. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam.Convallis aenean et tortor at risus viverra. Integer feugiat scelerisque varius morbi enim nunc faucibus a. Morbi non arcu risus quis varius quam quisque. Ut eu sem integer vitae justo eget magna fermentum. Ante in nibh mauris cursus mattis molestie a iaculis at.",
    price: 20,
    quantity: 5,
    release: "03/25/2020",
  },
  {
    id: 13,
    img: "https://i1.wp.com/cuttongarments.com/wp-content/uploads/2017/10/yellow-gold-copy-1.png?fit=538%2C538&ssl=1",
    size: ["M", "L"],
    color: ["yellow"],
    cat: ["shirt"],
    title: "Modern Shirt",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod lacinia at quis risus sed vulputate odio. In pellentesque massa placerat duis ultricies. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam.Convallis aenean et tortor at risus viverra. Integer feugiat scelerisque varius morbi enim nunc faucibus a. Morbi non arcu risus quis varius quam quisque. Ut eu sem integer vitae justo eget magna fermentum. Ante in nibh mauris cursus mattis molestie a iaculis at.",
    price: 18,
    quantity: 5,
    release: "03/25/2020",
  },
  {
    id: 14,
    img: "https://th.bing.com/th/id/R.6101e5982e52257cbb200b4ff7095825?rik=6QNsEBa05qBHJg&riu=http%3a%2f%2fpngimg.com%2fuploads%2fpolo_shirt%2fpolo_shirt_PNG8149.png&ehk=%2bwu1kNdSaz%2bDdRO2lAyb80kjXGFejXjILWmtX3uLZ%2bs%3d&risl=1&pid=ImgRaw&r=0",
    size: ["M", "L"],
    color: ["pink"],
    cat: ["shirt"],
    title: "Stylish Shirt",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod lacinia at quis risus sed vulputate odio. In pellentesque massa placerat duis ultricies. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam.Convallis aenean et tortor at risus viverra. Integer feugiat scelerisque varius morbi enim nunc faucibus a. Morbi non arcu risus quis varius quam quisque. Ut eu sem integer vitae justo eget magna fermentum. Ante in nibh mauris cursus mattis molestie a iaculis at.",
    price: 15,
    quantity: 5,
    release: "03/25/2020",
  },
  {
    id: 15,
    img: "https://th.bing.com/th/id/R.6c8c0df02818c0239c62b6712df32861?rik=KJjUBdupBHQZhg&riu=http%3a%2f%2fpngimg.com%2fuploads%2fpolo_shirt%2fpolo_shirt_PNG8166.png&ehk=ycsVnFdnDYj8t%2fh9MqR1dtwWB1du%2fYH7uf8Eu%2bdIoXc%3d&risl=&pid=ImgRaw&r=0",
    size: ["M", "L"],
    color: ["whitesmoke"],
    cat: ["shirt"],
    title: "White Shirt",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod lacinia at quis risus sed vulputate odio. In pellentesque massa placerat duis ultricies. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam.Convallis aenean et tortor at risus viverra. Integer feugiat scelerisque varius morbi enim nunc faucibus a. Morbi non arcu risus quis varius quam quisque. Ut eu sem integer vitae justo eget magna fermentum. Ante in nibh mauris cursus mattis molestie a iaculis at.",
    price: 25,
    quantity: 5,
    release: "03/25/2020",
  },
];

export const users = [];
